name: RilliyaVADriver

options:
  minimumXcodeGenVersion: 2.46.0
  xcodeVersion: "26.3"
  projectFormat: xcode16_3
  defaultConfig: Debug
  deploymentTarget:
    macOS: "14.2"

settings:
  base:
    CODE_SIGN_IDENTITY: "${CODE_SIGN_IDENTITY}"

targets:
  RilliyaVADriver:
    type: bundle
    platform: macOS
    sources:
      - path: Sources
      - path: Generated/ProductConfiguration.hpp
        buildPhase: headers
    configFiles:
      Debug: Generated/ProductConfiguration.xcconfig
      Release: Generated/ProductConfiguration.xcconfig
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        CLANG_CXX_LANGUAGE_STANDARD: c++20
        CURRENT_PROJECT_VERSION: 1
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Resources/Info.plist
        INSTALL_PATH: /Library/Audio/Plug-Ins/HAL
        MACH_O_TYPE: mh_bundle
        MARKETING_VERSION: 0.1.0-alpha.1
        SKIP_INSTALL: NO
        WRAPPER_EXTENSION: driver
      configs:
        Release:
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
          COPY_PHASE_STRIP: YES
          DEAD_CODE_STRIPPING: YES
          DEPLOYMENT_POSTPROCESSING: YES
          LLVM_LTO: YES_THIN
          STRIP_INSTALLED_PRODUCT: YES
          STRIP_STYLE: non-global
    dependencies:
      - sdk: CoreAudio.framework
      - sdk: CoreFoundation.framework
